### ISSUE TITLE
allowPaste not woking (browser supports paste)

### ISSUE THREAD

**Issue by Hellek** [pqina/vue-filepond#11]
Short example
`<FilePond :allowPaste="true" />`
Here pressing of "ctrl + v" not cause effect

But here cause
```
handleFilePondInit: function() {
   // console.log('FilePond has initialized');
   // FilePond instance methods are available on `this.$refs.pond`

   window.addEventListener('paste', (e) => {
      console.log('Cause effect!');
   });
},
```
How can i rethrow event to Pond?

**Comment by Hellek** [comment]
I tryed it at few, for example at latest Chrome
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"

Copypaste works at another websites. I guess that FilePond don't see paste event
window.addEventListener('paste', (e) => {});

**Comment by rikschennink** [comment]
Alright, will look into this later this week.

**Comment by rikschennink** [comment]
@Hellek FilePond does observe the `'paste'` event but pasting of files is ( as far as I can tell ) implemented poorly across browser. These are my test results. 

What other website did you test? I truly hope my test results are incorrect and this should work everywhere but I'm afraid native file copy-paste support is simply not there yet.

## MacOS

Firefox
- Might need to give copy paste approval in dev console
- Paste file works, but pastes the MacOS file icon instead of the file, and will rename the file to image.png :/

Chrome
- Pasting a text file or zip file does not work
- Pasting an image file works, but the image will always be converted to a PNG and renamed to image.png

Safari
- As far as I can tell pasting a file works on Safari


## Windows 10

Firefox
- Copy pasting of files does not work

Chrome
- Copy pasting of files does not work

Edge
- Copy pasting of files does not work

**Comment by Hellek** [comment]
I were not right. Paste works at https://vk.com/ just for screenshot from buffer, not for files.
My browser is listening 'paste' event, but don't do anything.
You are right that problem in poor browser support

**Comment by rikschennink** [comment]
@Hellek Thanks for confirming! Fingers crossed for better future support. 🤞
