### ISSUE TITLE
Create multiple filepond-Vue components by clicking add button 

### ISSUE THREAD

**Issue by wailashraf71** [pqina/vue-filepond#179]
I've created a tab with bootstrap that contains text fields and Filpond Vue upload component, then I've created a button to add new tabs via jquery with the same text fields and information, how can I append a new Filepond-Vue upload component to these new tabs? also, these components should have different name identifier to process their data with Laravel or PHP.

Please help ASAP 😥

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.

**Comment by wailashraf71** [comment]
@rikschennink what issue template?

**Comment by rikschennink** [comment]
@wailashraf71 It's in the textarea when you submit an issue.

---

**Describe the bug**
A clear and concise description of what the bug is.


**Logs**
Please include browser console and server logs around the time this bug occurred.


**To Reproduce**
To help us help you, if you've found a bug please consider the following:

* If you can demonstrate the bug, please do so by forking [this codesandbox](https://codesandbox.io/s/vue-filepond-v9ijm).
* If that's not possible, we recommend creating a small repo that illustrates the problem.
* Reproductions should be [small, self-contained, correct examples](http://sscce.org).

Occasionally, this won't be possible, and that's fine – we still appreciate you raising the issue. But please understand that the more details you provide, the more inclined others are to help you out and the faster the issue can be resolved.

Please [format code snippets](https://help.github.com/articles/creating-and-highlighting-code-blocks/) using triple backticks and set the appropriate language.


**Expected behavior**
A clear and concise description of what you expected to happen.


**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  Stack trace goes here...
</details>


**Information about your project:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 11)

- Your operating system: (e.x. MacOS 10, Ubuntu Linux 19.10, Windows 10, etc)

- FilePond version (Please check you can reproduce the issue with the latest release!)


**Additional context**
Add any other context about the problem here.

**Comment by wailashraf71** [comment]
@rikschennink I understand thanks but this not a bug, only a request for help about how to do this via Filepond as it should support multiple upload instances.

**Comment by rikschennink** [comment]
@wailashraf71 in that situation I kindly ask you to ask your question on Stack Overflow. See choices when clicking on new issue.

---

This issue tracker is intended to collect bug reports and feature requests.

For help with integrating FilePond, information on how features work, or questions about specific features of FilePond, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/filepond). Any issues open for help requests will be closed to keep from clogging up the issue tracker.

**Comment by wailashraf71** [comment]
@rikschennink Ok thank you
