### ISSUE TITLE
Wrong Server options (URL) on fetch

### ISSUE THREAD

**Issue by creazy231** [pqina/vue-filepond#78]
### Summary
Uploading images works fine. Now I want to fetch the uploaded image when the page is loaded but filepond uses wrong URL to fetch data.

### How to reproduce
![image](https://user-images.githubusercontent.com/13473174/54610776-f6838200-4a55-11e9-8d90-640b3ad578cb.png)

### Expected behaviour
Fetching the file using `http://localhost:3000` instead of the current href + file.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Browser      | Chrome

**Comment by gassius** [comment]
if you don't define a different fetch configuration, its expected to use localhost:3000 as it is the server you defined. Your server need to download that file from a third party server, save it to a tmp file and provide it back to FilePond. FilePond won't request the file directly because CORS policies might block it.
In any case, it seems like you need to do a load instead of a fetch. The way I use it, 'load' is for files already uploaded in a server I control (for example, attachments to a form) and 'fetch' is more for getting new file for uploads from different servers, as for example, when you do a Google Image Search and provide an url.
I hope this helps

**Comment by creazy231** [comment]
In my case I want to load the image from my backend (direkt url or api file response) and put this file into the filepond object. Therewith the user will be able to delete the file and upload a new one but I'm not able to get the image using direkt url or api file response because filepond tries to get the file using a wrong url, even if I provide die correct endpoint.

**Comment by gassius** [comment]
@creazy231 then for sure you need to use load instead of fetch
In the example you provided, FilePond will try to load any from localhost:3000/?load={fileId}

I strongly recommend you setup a different endpoint as for example:
```javascript
setOptions({
  server: 'http://localhost:3000',
  load: {
     url: './load'
  }
  files: arrayOfFilesToLoad
})
```
for load to work, you need to provide an array of File objects as for example:
```javascript
var fileObj = {
                // the server file reference
                source: ID,

                // set type to local to indicate an already uploaded file
                options: {
                    type: 'local'
            }
var arrayOfFilesToLoad = [fileObj]
```

**Comment by creazy231** [comment]
This example helped me a lot <3 Thanks
